# Generated by Django 5.2 on 2025-04-17 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menue',
            new_name='Menu',
        ),
    ]
